
CREATE SCHEMA IF NOT EXISTS mysql DEFAULT CHARACTER SET utf8;
USE mysql;

CREATE TABLE  IF NOT EXISTS mysql.tb_chavepix (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  telefone VARCHAR(20),
  email VARCHAR(255),
  cpf VARCHAR(14),
  chave_aleatoria VARCHAR(50)
);

