version: '3.8'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mysql"
      MYSQL_USER: "chavepix"
      MYSQL_PASSWORD: "12342023"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    restart: always
    networks:
      - minha-rede

networks: 
  minha-rede:
    driver: bridge

volumes:
db: